# Data paths
DATA_BACKGROUND_FOLDER = "../data/background/"
DATA_GENERATED_FOLDER = "../data/generated_data/"

# General settings
IMAGES_TO_GENERATE = 500
COIN_RESIZE_RATIO_MIN = 0.4
COIN_RESIZE_RATIO_MAX = 0.6

# Background settings
BACKGROUND_RESIZE_RATIO = 400
BACKGROUND_MAX_N_COINS = 25

# Coin crop settings
MAX_COIN_OVERLAP_PERCENTAGE = 0.33
INDIVIDUAL_COIN_CROP_NOISE = 0.05
